=== Trettende/EpamJavaTraining/input.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://nure.ua/matchenko/practice7"
            xmlns:tns="http://nure.ua/matchenko/practice7">

    <xsd:element name="SteelArm">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Knife" type="tns:Knife" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Knife">
        <xsd:sequence>
            <xsd:element name="Type" type="xsd:string"/>
            <xsd:element name="Handy">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="one-handed"/>
                        <xsd:enumeration value="two-handed"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Origin" type="xsd:string"/>
            <xsd:element name="Visual" type="tns:Visual" maxOccurs="unbounded"/>
            <xsd:element name="Value" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Visual">
        <xsd:sequence>
            <xsd:element name="Blade" type="tns:Blade"></xsd:element>
            <xsd:element name="Material" type="tns:Material"></xsd:element>
            <xsd:element name="Bloodstream" type="xsd:boolean"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Blade">
        <xsd:sequence>
            <xsd:element name="Length">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="10"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Width">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="10"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Material">
        <xsd:sequence>
            <xsd:element name="BladeMaterial" type="xsd:string"/>
            <xsd:choice>
                <xsd:element name="Handle" type="xsd:string"/>
                <xsd:sequence>
                    <xsd:element name="WoodHandle" type="xsd:string"/>
                    <xsd:element name="WoodType" type="xsd:string"/>
                </xsd:sequence>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Trettende/EpamJavaTraining/input.xml
<?xml version="1.0" encoding="UTF-8" ?>

<p7:SteelArm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:p7="http://nure.ua/matchenko/practice7"
    xsi:schemaLocation="http://nure.ua/matchenko/practice7 input.xsd">
    <Knife>
        <Type>knife</Type>
        <Handy>one-handed</Handy>
        <Origin>Sweden</Origin>
        <Visual>
            <Blade>
                <Length>10</Length>
                <Width>12</Width>
            </Blade>
            <Material>
                <BladeMaterial>steel</BladeMaterial>
                <WoodHandle>wooden</WoodHandle>
                <WoodType>oak</WoodType>
            </Material>
            <Bloodstream>true</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>17</Length>
                <Width>16</Width>
            </Blade>
            <Material>
                <BladeMaterial>iron</BladeMaterial>
                <Handle>onion</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>true</Value>
    </Knife>

    <Knife>
        <Type>dagger</Type>
        <Handy>one-handed</Handy>
        <Origin>USA</Origin>
        <Visual>
            <Blade>
                <Length>15</Length>
                <Width>18</Width>
            </Blade>
            <Material>
                <BladeMaterial>cast iron</BladeMaterial>
                <Handle>plastic</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>18</Length>
                <Width>17</Width>
            </Blade>
            <Material>
                <BladeMaterial>wooden</BladeMaterial>
                <WoodHandle>wooden</WoodHandle>
                <WoodType>tree</WoodType>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>false</Value>
    </Knife>

    <Knife>
        <Type>saber</Type>
        <Handy>two-handed</Handy>
        <Origin>France</Origin>
        <Visual>
            <Blade>
                <Length>25</Length>
                <Width>20</Width>
            </Blade>
            <Material>
                <BladeMaterial>copper</BladeMaterial>
                <WoodHandle>wooden</WoodHandle>
                <WoodType>pine</WoodType>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>10</Length>
                <Width>12</Width>
            </Blade>
            <Material>
                <BladeMaterial>steel</BladeMaterial>
                <WoodHandle>wooden</WoodHandle>
                <WoodType>oak</WoodType>
            </Material>
            <Bloodstream>true</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>15</Length>
                <Width>18</Width>
            </Blade>
            <Material>
                <BladeMaterial>cast iron</BladeMaterial>
                <Handle>plastic</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>true</Value>
    </Knife>

</p7:SteelArm>

=== Trettende/EpamJavaTraining/output.stax.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<p7:SteelArm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://nure.ua/matchenko/practice7 input.xsd"
             xmlns:p7="http://nure.ua/matchenko/practice7">
    <Knife>
        <Type>knife</Type>
        <Handy>one-handed</Handy>
        <Origin>Sweden</Origin>
        <Visual>
            <Blade>
                <Length>10</Length>
                <Width>12</Width>
            </Blade>
            <Material>
                <BladeMaterial>steel</BladeMaterial>
                <Handle/>
            </Material>
            <Bloodstream>true</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>17</Length>
                <Width>16</Width>
            </Blade>
            <Material>
                <BladeMaterial>iron</BladeMaterial>
                <Handle>onion</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>true</Value>
    </Knife>
    <Knife>
        <Type>saber</Type>
        <Handy>two-handed</Handy>
        <Origin>France</Origin>
        <Visual>
            <Blade>
                <Length>25</Length>
                <Width>20</Width>
            </Blade>
            <Material>
                <BladeMaterial>copper</BladeMaterial>
                <Handle/>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>10</Length>
                <Width>12</Width>
            </Blade>
            <Material>
                <BladeMaterial>steel</BladeMaterial>
                <Handle/>
            </Material>
            <Bloodstream>true</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>15</Length>
                <Width>18</Width>
            </Blade>
            <Material>
                <BladeMaterial>cast iron</BladeMaterial>
                <Handle>plastic</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>true</Value>
    </Knife>
    <Knife>
        <Type>dagger</Type>
        <Handy>one-handed</Handy>
        <Origin>USA</Origin>
        <Visual>
            <Blade>
                <Length>15</Length>
                <Width>18</Width>
            </Blade>
            <Material>
                <BladeMaterial>cast iron</BladeMaterial>
                <Handle>plastic</Handle>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Visual>
            <Blade>
                <Length>18</Length>
                <Width>17</Width>
            </Blade>
            <Material>
                <BladeMaterial>wooden</BladeMaterial>
                <Handle/>
            </Material>
            <Bloodstream>false</Bloodstream>
        </Visual>
        <Value>false</Value>
    </Knife>
</p7:SteelArm>
